version: '2'
services:
    pandoc:
        image: silviof/docker-pandoc
        volumes:
#            - ./files.txt:/files.txt
            - ./build_doc.sh:/build_doc.sh
        entrypoint: /build_doc.sh